apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: producer
  name: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  strategy: {}
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - image: rampi88/sample-producer:v1
        name: sample-producer
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.1"
            memory: "256Mi"
        volumeMounts:
          - name: client-properties
            mountPath: "/client.properties"
            subPath: client.properties
      volumes:
      - name: client-properties
        configMap:
          name: client-properties
          items:
          - key: client.properties
            path: client.properties